name: Update Discord Card

on:
  schedule:
    - cron: '*/5 * * * *'  # Her 5 dakikada bir tetikleme
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Install Puppeteer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3

      - name: Install dependencies
        run: npm install

      - name: Generate Discord Card
        run: npm run generate:card

      - name: Debugging Info (Opsiyonel)
        run: env

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add discord-card.png
          git commit -m "Update discord-card.png" --allow-empty
          git push
