name: Update Discord Card

on:
  schedule:
    - cron: '*/5 * * * *'  # Her 5 dakikada bir tetiklenir

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'false'

      - name: Generate Discord Card
        run: npm run generate:card

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add discord-card.png
          git commit -m "Update discord-card.png" --allow-empty
          git push
