name: Update Discord Card

on:
  workflow_dispatch:    # Manuel çalıştırma için
  schedule:
    - cron: '0 * * * *' # Örnek: her saat başı çalışır

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Generate Discord Card
        run: node scripts/generateDiscordCard.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add discord-card.png
          git commit -m "Update discord-card.png"
          git push
          
